apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtsp
  name: rtsp-service
spec:
  ports:
  - port: 8554
    protocol: TCP
    targetPort: 8554
    nodePort: 32554
  selector:
    app: rtsp
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp
  labels:
    app: rtsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp
  template:
    metadata:
      labels:
        app: rtsp
    spec:
      containers:
      - name: rtsp
        image: gar-registry.caas.intel.com/virtiot/haven-eflow
        command: ["/root/rtsp.sh"]
        ports:
        - containerPort: 8554
