apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogIkVGTE9XIgogIHNjcmFwZV9pbnRlcnZhbDogNXMKICBzdGF0aWNfY29uZmlnczoKICAtIHRhcmdldHM6IFsiMTAuMjI2Ljc2LjkwOjkxMDAiLCIxMC4yMjYuNzYuOTA6OTE4MiIsIjEwLjIyNi43Ni45MDozMDAwIl0K
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
