apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogIkVGTE9XIgogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czogWyIxMC4yMjYuNzYuOTA6OTEwMCIsIjEwLjIyNi43Ni45MDo5MTgyIiwiMTAuMjI2Ljc2LjkwOjMwMDAiXQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
